# Dependabot configuration for automated dependency updates
# For more configuration options, see: https://docs.github.com/en/code-security/supply-chain-security/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"
    labels:
      - "dependencies"
    commit-message:
      prefix: "deps"
